TwitterForZombies/config/routes.rb
TwitterForZombies::Application.routes.draw do
  resources :zombies
  root :to=> "zombies#index"
  get "signin" => "zombies#signin"
  get "signedout" => "zombies#signedout"
  get "home" => "zombies#index"
  get "register" => "zombies#new" 
  post "signin" => "zombies#login"
  get "forgot_password" => "zombies#forgot_password" 
  put "forgot_password" => "zombies#send_password_reset_instructions"

  get "password_reset" => "zombies#password_reset"
  put "password_reset" => "zombies#new_password"

  get "listing" => "zombies#listing"

  get "tweets" => "tweets#new"
  post "tweets" => "tweets#create"

  get "mytweets" => "tweets#list"

  get "alltweets" => "tweets#alltweets"
  
  get "updatelikes" => "tweets#updatelikes"
 
  get "updatedislikes" => "tweets#updatedislikes"

  get "following" => "zombies#following"
  
  get "unfollowing" => "zombies#unfollowing"

end

TwitterForZombies/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie 
end

TwitterForZombies/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


  def list 
    zombie = current_user.id   
    @tweet = Tweet.where(zombie_id:current_user.id)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet}
    end
  end

  def updatelikes
    @tweet = Tweet.find(params[:id])
    @tweet.likes += 1   
    @tweet.likedby+=current_user.id.to_s()+","    
    @tweet.save
    redirect_to :root
  end

  def updatedislikes
    @tweet = Tweet.find(params[:id])
    @tweet.likes -= 1       
    example = @tweet.likedby
    example = example.gsub(current_user.id.to_s+",","")
    @tweet.likedby = example
    @tweet.save
    redirect_to :root
  end

  def alltweets
    @tweet = Tweet.all
    @compare = true
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet}
    end
  end

  def new
    @tweet = Tweet.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet}
    end
  end

  def create
    @tweet = Tweet.new(params[:tweet])
    @tweet.zombie_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to :root }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "tweet" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

end

TwitterForZombies/app/views/tweets/alltweets.html.erb
<legend>All Tweets</legend>
<% @tweet.each do |tweet| %>

     <div class="status">
    <div class = "well" id="lol">
        <div class = "row">
           <div class="span1">
              <%= link_to image_tag(Zombie.find_by_id(tweet.zombie_id).gravatar_url),Zombie.find_by_id(tweet.zombie_id) %>
           </div>

           <div class="span7">

             <p class="text-info lead">
                <%=  tweet.status %>
             </p> 

    		     <% if !tweet.likedby.include? current_user.id.to_s %>                              
   		        	<a href="<%= updatelikes_path(:id=>tweet.id) %>"><button class="btn-info">Like</button></a>
           	 <% else %>              
   		        	<a href="<%= updatedislikes_path(:id=>tweet.id) %>"><button class="btn-danger">Unlike</button></a>         
 	  	       <% end %>

             <% if tweet.zombie_id!=current_user.id %>

	             <% if !current_user.following.include? tweet.zombie_id.to_s %>
  	              <%= link_to 'follow', following_path(:id=>tweet.zombie_id) %>
  	           <% end %>

               <% if current_user.following.include? tweet.zombie_id.to_s %>
  	              <%= link_to 'unfollow', unfollowing_path(:id=>tweet.zombie_id) %>
  	           <% end %>

             <% end %>

             <br>
             <%= time_ago_in_words(tweet.created_at) %>
             <br>

 			       
    			   <p class="muted">       
                Posted By-
      				  <%= link_to Zombie.find_by_id(tweet.zombie_id).username, Zombie.find_by_id(tweet.zombie_id) %>

  		       </p>
             </div>
          </div>
       </div>
     </div>     
  
<% end %>


<br />

TwitterForZombies/app/views/tweets/list.html.erb
<legend>Listing Tweets</legend>
<table class="table">
  <tr>
    <th>Username</th>
    <th>status</th>
    <th>id</th>
    <th>likes</th>
    <th>liked by</th>
  </tr>

<% @tweet.each do |tweet| %>
  <tr>
    <td><%= current_user.username %></td>
    <td><%=  tweet.status %></td>
    <td><%=  tweet.zombie_id %></td>
    <td><%= tweet.likes %></td>
    <td><%= tweet.likedby %></td>
  </tr>
<% end %>
</table>

<br />

TwitterForZombies/app/views/tweets/new.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_area :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>