TwitterForZombies/config/routes.rb
TwitterForZombies::Application.routes.draw do
  resources :zombies
  root :to=> "zombies#index"
  get "signin" => "zombies#signin"
  get "signedout" => "zombies#signedout"
  get "home" => "zombies#index"
  get "register" => "zombies#new" 
  post "signin" => "zombies#login"
  get "forgot_password" => "zombies#forgot_password" 
  put "forgot_password" => "zombies#send_password_reset_instructions"

  get "password_reset" => "zombies#password_reset"
  put "password_reset" => "zombies#new_password"

  get "listing" => "zombies#listing"

  get "tweets" => "tweets#new"
  post "tweets" => "tweets#create"

  get "mytweets" => "tweets#list"

  get "alltweets" => "tweets#alltweets"
  
  get "updatelikes" => "tweets#updatelikes"
 
  get "updatedislikes" => "tweets#updatedislikes"

  get "following" => "zombies#following"
  
  get "unfollowing" => "zombies#unfollowing"

end

TwitterForZombies/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  def listing
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end
 
  def signin
    @zombie = Zombie.new
  end

  def signedout
    zombie = Zombie.find_by_id(session[:zombie_id])

    if zombie
      update_authentication_token(zombie, nil)
      zombie.save
      session[:zombie_id] = nil      
      redirect_to :root
    else
      redirect_to :signin
    end
  end

  def login
    username_or_email = params[:zombie][:username]
    password = params[:zombie][:password]

    if username_or_email.rindex('@')
      email=username_or_email
      zombie = Zombie.authenticate_by_email(email, password)
    else
      username=username_or_email
      zombie = Zombie.authenticate_by_username(username, password)
    end

    if zombie      
      update_authentication_token(zombie, params[:zombie][:remember_me])
      zombie.save
      session[:zombie_id] = zombie.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      render :action => "signin"
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])
    example = @zombie.following
    example = example[0,example.length-1]
    @tweet = Tweet.where("zombie_id in (#{example})")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end


  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        # ZombieMailer.welcome_email(@zombie).deliver
        session[:zombie_id] = @zombie.id
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
    end
  end
  
  def following
    example = params[:id]
    @zombie = current_user
    @zombie.following+=example.to_s()+","
    @zombie.save 
    redirect_to :root
  end

  def unfollowing
    example = params[:id]
    @zombie = current_user
    @zombie.following = @zombie.following.gsub(example.to_s()+",","")
    @zombie.save
    redirect_to :root
  end

# HTTP get
def forgot_password
  @zombie = Zombie.new
end

# HTTP put
def send_password_reset_instructions
  username_or_email = params[:zombie][:username]

  if username_or_email.rindex('@')
    zombie = Zombie.find_by_email(username_or_email)
  else
    zombie = Zombie.find_by_username(username_or_email)
  end

  if zombie
    zombie.password_reset_token = SecureRandom.urlsafe_base64
    zombie.password_expires_after = 24.hours.from_now
    zombie.save
    ZombieMailer.reset_password_email(zombie).deliver
    #flash[:notice] = 'Password instructions have been mailed to you. Please check your inbox.'
    redirect_to :signin
  else
    @zombie = Zombie.new
    # put the previous value back.
    @zombie.username = params[:zombie][:username]
    @zombie.errors[:username] = 'is not a registered user.'
    render :action => "forgot_password"
  end
end


def password_reset
  token = params.first[0]
  @zombie = Zombie.find_by_password_reset_token(token)

  if @zombie.nil?
    flash[:error] = 'You have not requested a password reset.'
    redirect_to :root
    return
  end

  if @zombie.password_expires_after < DateTime.now
    clear_password_reset(@zombie)
    @zombie.save
    flash[:error] = 'Password reset has expired. Please request a new password reset.'
    redirect_to :forgot_password
  end
end

def new_password
  username = params[:zombie][:username]
  @zombie = Zombie.find_by_username(username)

  if verify_new_password(params[:zombie])
    @zombie.update_attributes(params[:zombie])
    @zombie.password = @zombie.new_password

    if @zombie.valid?
      clear_password_reset(@zombie)
      @zombie.save
      flash[:notice] = 'Your password has been reset. Please sign in with your new password.'
      redirect_to :signin
    else
      render :action => "password_reset"
    end
  else
    @zombie.errors[:new_password] = 'Cannot be blank and must match the password verification.'
    render :action => "password_reset"
  end
end

private

	def clear_password_reset(zombie)
 	 zombie.password_expires_after = nil
  	zombie.password_reset_token = nil
	end

  def verify_new_password(passwords)
    result = true

    if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
      result = false
    end

    result
  end

  def update_authentication_token(zombie, remember_me)
    if remember_me == 1
      # create an authentication token if the user has clicked on remember me
      auth_token = SecureRandom.urlsafe_base64
      zombie.authentication_token = auth_token
      cookies.permanent[:auth_token] = auth_token
    else              # nil or 0
      # if not, clear the token, as the user doesn't want to be remembered.
      zombie.authentication_token = nil
      cookies.permanent[:auth_token] = nil
    end
  end


end

TwitterForZombies/app/helpers/zombies_helper.rb
module ZombiesHelper
end

TwitterForZombies/app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label 'password:' %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label 'password confirmation:' %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TwitterForZombies/app/views/zombies/account_settings.html.erb
<%= form_for @zombie, :as => :zombie, :url => account_settings_path(@zombie), :method=>:post do |f| %>
  <p>
    <%= f.label 'old password' %><br/>
    <%= f.password_field :password %>    
  </p>
  <p>
    <%= f.label 'new password' %><br/>
    <%= f.password_field :new_password %>    
  </p>
  <p>
    <%= f.label 'new_password confirmation' %><br/>
    <%= f.password_field :new_password_confirmation %>    
  </p>
  <p>
    <%= f.submit 'Update' %>&nbsp;&nbsp;&nbsp;
    <%= f.submit 'Clear Form', :type => 'reset' %>
  </p>
<% end %>

TwitterForZombies/app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

TwitterForZombies/app/views/zombies/forgot_password.html.erb
<p>Forgot Password</p>
<%= form_for @zombie, :as => :zombie, :url => forgot_password_path, :method => :put do |f| %>
  <p>
    <%= f.label 'username or email:' %><br/>
    <%= f.text_field :username %>    
  </p>
  <p>
    <%= f.submit 'Send Password Reset Instructions' %>
  </p>
<% end %>

TwitterForZombies/app/views/zombies/index.html.erb
      <div class="jumbotron">
        <h1>Twitter For Zombies</h1>
        <p class="lead">Register as a Zombie and tweet your way through the ranks.Start as a novice zombie and move up the ranks to create factions and bid against other teams to claim the top Zombie Spot. So Register today and start tweeting</p>
        <a class="btn btn-large btn-success" href="#">Get started today</a>
      </div>

      <hr>

      <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

TwitterForZombies/app/views/zombies/listing.html.erb
<legend>Listing Zombies</legend>

<table>
  <tr>
    <th>Username</th>
    <th>Age</th>
    <th>Bio</th>
    <th>Email</th>
    <th>Rotting</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.username %></td>
    <td><%= zombie.age %></td>
    <td><%= zombie.bio %></td>
    <td><%= zombie.email %></td>
    <td><%= zombie.rotting %></td>
    <td><%= zombie.tweets[0] %></td>
    <% if current_user %>
      <% if current_user.username == zombie.username %>
        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, confirm: 'Are you sure?', method: :delete %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<br />

TwitterForZombies/app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

TwitterForZombies/app/views/zombies/password_reset.html.erb
<p>Account Settings</p>
<%= form_for @zombie, :as => :zombie, :url => password_reset_path, :method => :put do |f| %>
  <p>
    <%= @zombie.username %> has requested a password reset. Please enter your new password:
  </p>
  <p>
    <%= f.label 'new password:' %><br/>
    <%= f.password_field :new_password %>    
  </p>
  <p>
    <%= f.hidden_field :username %>
    <%= f.label 'password confirmation:' %><br/>
    <%= f.password_field :new_password_confirmation %>    
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

TwitterForZombies/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @zombie.username %>
</p>

<p>
  <b>Age:</b>
  <%= @zombie.age %>
</p>

<p>
  <b>Bio:</b>
  <%= @zombie.bio %>
</p>

<p>
  <b>Email:</b>
  <%= @zombie.email %>
</p>

<p>
  <b>Rotting:</b>
  <%= @zombie.rotting %>
</p>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>

TwitterForZombies/app/views/zombies/signin.html.erb
<p>Sign In</p>
<%= form_for @zombie, :as => :zombie, :url => signin_path(@zombie) do |f| %>
  <p>
    <%= f.label 'username or email:' %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label 'password:' %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :remember_me %>
  </p>
  <p>
    <%= link_to 'forgot your password?', :forgot_password %>
  </p>
  <p>
    <%= f.submit 'Sign In' %>&nbsp;&nbsp;&nbsp;
    <%= f.submit 'Clear Form', :type => 'reset' %>
  </p>
<% end %>